/**
 * TrimCity — All UI strings
 * i18n-ready: keep all user-facing text here.
 * Future: wrap with i18next or similar.
 */
export const Strings = {
  app: {
    name: 'TrimCity',
    tagline: 'Find & Book Salons Near You',
    version: '1.0.0',
  },

  auth: {
    welcomeTitle: 'Welcome to TrimCity',
    welcomeSubtitle: 'Book your next haircut in seconds',
    phoneLabel: 'Mobile Number',
    phonePlaceholder: 'Enter your 10-digit mobile number',
    phoneHint: 'We will send an OTP to verify',
    sendOtp: 'Send OTP',
    otpTitle: 'Verify Your Number',
    otpSubtitle: (phone: string) => `OTP sent to +91 ${phone}`,
    otpLabel: 'Enter 6-digit OTP',
    verifyOtp: 'Verify & Continue',
    resendOtp: 'Resend OTP',
    resendIn: (sec: number) => `Resend in ${sec}s`,
    changeNumber: 'Change Number',
    loginAsOwner: 'Login as Salon Owner',
    loginAsCustomer: 'Book an Appointment',
    otpSent: 'OTP sent successfully!',
    otpError: 'Invalid OTP. Please try again.',
    phoneError: 'Please enter a valid 10-digit mobile number.',
    networkError: 'No internet connection. Please check your network.',
  },

  home: {
    screenTitle: 'Explore Salons',
    searchPlaceholder: 'Search by salon name or area…',
    statsOpen: 'Open Now',
    statsTotalSalons: 'Total Salons',
    statsSeated: 'Customers Seated',
    statsWaiting: 'People Waiting',
    filters: {
      all: 'All',
      availableNow: 'Available Now',
      lowWait: 'Low Wait',
      topRated: 'Top Rated',
      men: 'Men',
      women: 'Women',
      unisex: 'Unisex',
    },
    emptyTitle: 'No Salons Found',
    emptySubtitle: 'Try a different search or filter',
    liveLabel: 'LIVE',
    loadingText: 'Finding salons near you…',
  },

  salonDetail: {
    screenTitle: 'Salon Details',
    seatedNow: 'Seated Now',
    totalSeats: 'Total Seats',
    currentlyWaiting: 'Currently Waiting',
    services: 'Services & Pricing',
    location: 'Location',
    bookAppointment: 'Book Appointment',
    yourName: 'Your Full Name',
    yourPhone: 'Your Phone Number',
    selectService: 'Select a Service',
    selectTimeSlot: 'Select Time Slot',
    confirmBooking: 'Confirm Booking',
    bookedSlot: 'Booked',
    availableSlot: 'Available',
    closed: 'Closed Today',
    openNow: 'Open Now',
    contactSalon: 'Contact Salon',
    duration: (min: number) => `${min} min`,
    price: (amount: number) => `₹${amount}`,
  },

  confirmation: {
    title: 'Booking Confirmed!',
    subtitle: 'Your appointment has been booked',
    appointmentDetails: 'Appointment Details',
    getDirections: 'Get Directions',
    viewBookings: 'View My Bookings',
    shareBooking: 'Share',
    addToCalendar: 'Add to Calendar',
  },

  appointments: {
    screenTitle: 'My Appointments',
    upcoming: 'Upcoming',
    past: 'Past',
    emptyUpcoming: 'No upcoming appointments',
    emptyUpcomingSubtitle: 'Book your next haircut now!',
    emptyPast: 'No past appointments',
    status: {
      confirmed: 'Confirmed',
      waiting: 'Waiting',
      completed: 'Completed',
      cancelled: 'Cancelled',
    },
    cancelBooking: 'Cancel Appointment',
    cancelConfirmTitle: 'Cancel Appointment?',
    cancelConfirmMessage: 'This action cannot be undone.',
    cancelConfirm: 'Yes, Cancel',
    cancelDismiss: 'Keep Appointment',
    getDirections: 'Directions',
  },

  profile: {
    screenTitle: 'My Profile',
    editProfile: 'Edit Profile',
    name: 'Full Name',
    phone: 'Phone Number',
    photo: 'Profile Photo',
    bookingHistory: 'Booking History',
    settings: 'Settings',
    logout: 'Logout',
    logoutConfirm: 'Are you sure you want to logout?',
    logoutConfirmYes: 'Logout',
    logoutConfirmNo: 'Cancel',
    notificationsEnabled: 'Push Notifications',
    version: (v: string) => `Version ${v}`,
  },

  ownerDashboard: {
    screenTitle: 'Owner Dashboard',
    todayBookings: "Today's Bookings",
    seatedNow: 'Seated Now',
    waitingNow: 'Waiting Queue',
    liveQueue: 'Live Queue',
    markSeated: 'Mark Seated',
    markCompleted: 'Mark Done',
    addWalkIn: 'Add Walk-in',
    noQueue: 'Queue is empty',
    refreshing: 'Refreshing…',
  },

  salonSetup: {
    screenTitle: 'Salon Profile',
    salonName: 'Salon Name',
    address: 'Full Address',
    pinLocation: 'Pin Location on Map',
    category: 'Category',
    totalSeats: 'Total Seats',
    services: 'Services',
    addService: 'Add Service',
    serviceName: 'Service Name',
    duration: 'Duration (minutes)',
    price: 'Price (₹)',
    photos: 'Salon Photos',
    addPhoto: 'Add Photo',
    workingHours: 'Working Hours',
    openTime: 'Open',
    closeTime: 'Close',
    saveProfile: 'Save Profile',
    categories: {
      men: 'Men',
      women: 'Women',
      unisex: 'Unisex',
    },
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  },

  bookingManagement: {
    screenTitle: 'Booking Management',
    upcoming: 'Upcoming',
    confirmBooking: 'Confirm',
    rejectBooking: 'Reject',
    addWalkIn: 'Add Walk-in Customer',
    walkInName: 'Customer Name',
    walkInPhone: 'Phone Number',
    walkInService: 'Service',
    addToQueue: 'Add to Queue',
    emptyBookings: 'No bookings yet',
  },

  errors: {
    generic: 'Something went wrong. Please try again.',
    network: 'No internet connection.',
    notFound: 'Not found.',
    unauthorized: 'You are not authorized to perform this action.',
    sessionExpired: 'Session expired. Please login again.',
    invalidInput: 'Please check your input.',
  },

  notifications: {
    bookingConfirmedTitle: 'Booking Confirmed!',
    bookingConfirmedBody: (salon: string, time: string) =>
      `Your appointment at ${salon} is confirmed for ${time}`,
    reminderTitle: 'Appointment Reminder',
    reminderBody: (salon: string) =>
      `Your appointment is in 1 hour at ${salon}`,
    newBookingTitle: 'New Booking Received',
    newBookingBody: (name: string, service: string, time: string) =>
      `${name} • ${service} • ${time}`,
    turnNearTitle: 'Your Turn is Near!',
    turnNearBody: (ahead: number, salon: string) =>
      `${ahead} person ahead of you. Get ready at ${salon}!`,
    cancelledTitle: 'Booking Cancelled',
    cancelledBody: 'Your booking has been cancelled. Slot is now free.',
  },
} as const;
